car_collection/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_marshmallow import Marshmallow
import uuid

from werkzeug.security import generate_password_hash

import secrets

from datetime import datetime

from flask_login import UserMixin, LoginManager


db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    first_name = db.Column(db.String, nullable = True, default = '')
    last_name = db.Column(db.String, nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = True, default = '')
    token = db.Column(db.String, default = '', unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow())
    car = db.relationship('Car', backref = 'owner', lazy = True)

    def __init__(self, email, first_name = '', last_name = '', id = '', password = '', token = ''):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token(24)

    def set_token(self, length):
        return secrets.token_hex(length)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
        return self.password_hash

    def __repr__(self):
        return f"User {self.email} has been added to the database!"


class Car(db.Model):
    id = db.Column(db.String, primary_key = True)
    make = db.Column(db.String(150))
    model = db.Column(db.String(150))
    year = db.Column(db.Integer)
    color = db.Column(db.String(50))
    mileage = db.Column(db.Integer)
    price = db.Column(db.Numeric(precision=10, scale=2))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, make, model, year, color, mileage, price, user_token, id = ''):
        self.id = self.set_id()
        self.make = make
        self.model = model
        self.year = year
        self.color = color
        self.mileage = mileage
        self.price = price
        self.user_token = user_token

    def __repr__(self):
        return f"The following {self.name} car has been added!"

    def set_id(self):
        return secrets.token_urlsafe()

    
class CarSchema(ma.Schema):
    class Meta:
        fields = ['id', 'make', 'model', 'year', 'color', 'mileage', 'price']

car_schema = CarSchema()
cars_schema = CarSchema(many = True)

car_collection/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email


class UserLoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    first_name = StringField('First Name')
    last_name = StringField('Last Name')
    password = PasswordField('Password', validators = [DataRequired()])
    submit_button = SubmitField()

car_collection/__init__.py
from flask import Flask
from .site.routes import site
from .auth.routes import auth
from .api.routes import api
from .models import db as root_db, login_manager, ma
from config import Config
from car_collection.helpers import JSONEncoder
from flask_migrate import Migrate

from flask_cors import CORS



app = Flask(__name__)
app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)


app.config.from_object(Config)

root_db.init_app(app)
migrate = Migrate(app, root_db)

login_manager.init_app(app)
login_manager.login_view = 'auth.signin'

ma.init_app(app)
app.json_encoder = JSONEncoder

CORS(app)

car_collection/api/routes.py
from flask import Blueprint, request, jsonify
from car_collection.helpers import token_required
from car_collection.models import db, Car, car_schema, cars_schema

api = Blueprint('ap', __name__, url_prefix = '/api')


@api.route('/cars', methods = ['POST'])
@token_required
def create_car(current_user_token):
    make = request.json['make']
    model = request.json['model']
    year = request.json['year']
    color = request.json['color']
    mileage = request.json['mileage']
    price = request.json['price']
    user_token = current_user_token.token

    print(f"User Token: {current_user_token}")

    car = Car(make, model, year, color, mileage, price, user_token = user_token)

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)

    return jsonify(response)


@api.route('/cars', methods = ['GET'])
@token_required
def get_cars(current_user_token):
    owner = current_user_token.token
    cars = Car.query.filter_by(user_token = owner).all()
    response = cars_schema.dump(cars)
    return jsonify(response)


@api.route('/cars/<id>', methods = ['GET'])
@token_required
def get_car(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        car = Car.query.get(id)
        response = car_schema.dump(car)
        return jsonify(response)
    else:
        return jsonify({'message': 'Valid token required!'})


@api.route('/cars/<id>', methods = ['POST', 'PUT'])
@token_required
def car(current_user_token, id):
    car = Car.query.get(id)
    car.make = request.json['make']
    car.model = request.json['model']
    car.year = request.json['year']
    car.color = request.json['color']
    car.mileage = request.json['mileage']
    car.price = request.json['price']
    car.user_token = current_user_token.token    

    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)


@api.route('/cars/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_user_token, id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

car_collection/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def index():
    return render_template('index.html')


@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

car_collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Title</title>
</head>
<body>
    <nav class="ct-nav">
        <div>
            <img src="" alt="">
        </div>
        
        <!-- Nav Items -->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.index') }}">
                    <li>Home</li>
                </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        <li>Logout</li>
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up</li>
                    </a>
                {% endif %}
            </ul>
        </div>
    
    
    
    </nav>




    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_collection/templates/forms.html
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Email goes here!") }}
        </fieldset>
        <fieldset id=firstname-field>
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "First Name goes here!") }}
        </fieldset>
        <fieldset id=lastname-field>
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Last Name goes here!") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Password goes here!") }}
        </fieldset>

        {{ form.submit_button(class = 'btn btn-primary btn-block') }}

    </div>
</form>